tareas:
    path: /
    controller: App\Controller\TareaController::index

registro:
    path: /registro
    controller: App\Controller\UserController::registro

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
    